// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: protos/cloud.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CloudService_GetMasterKubeconfig_FullMethodName = "/protos.CloudService/GetMasterKubeconfig"
	CloudService_GetClusterVars_FullMethodName      = "/protos.CloudService/GetClusterVars"
	CloudService_GetCloudFileSecret_FullMethodName  = "/protos.CloudService/GetCloudFileSecret"
	CloudService_CreateCloudSecret_FullMethodName   = "/protos.CloudService/CreateCloudSecret"
	CloudService_DeleteCloudSecret_FullMethodName   = "/protos.CloudService/DeleteCloudSecret"
	CloudService_GetCloudSecret_FullMethodName      = "/protos.CloudService/GetCloudSecret"
	CloudService_GetCloudSecrets_FullMethodName     = "/protos.CloudService/GetCloudSecrets"
	CloudService_GetCephAccess_FullMethodName       = "/protos.CloudService/GetCephAccess"
	CloudService_GetSshKey_FullMethodName           = "/protos.CloudService/GetSshKey"
	CloudService_GetProxmoxApi_FullMethodName       = "/protos.CloudService/GetProxmoxApi"
	CloudService_CreateProxmoxApi_FullMethodName    = "/protos.CloudService/CreateProxmoxApi"
	CloudService_DeleteProxmoxApi_FullMethodName    = "/protos.CloudService/DeleteProxmoxApi"
	CloudService_GetProxmoxHost_FullMethodName      = "/protos.CloudService/GetProxmoxHost"
	CloudService_GetPveInventory_FullMethodName     = "/protos.CloudService/GetPveInventory"
	CloudService_GetVmVarsBlake_FullMethodName      = "/protos.CloudService/GetVmVarsBlake"
)

// CloudServiceClient is the client API for CloudService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CloudServiceClient interface {
	GetMasterKubeconfig(ctx context.Context, in *GetKubeconfigRequest, opts ...grpc.CallOption) (*GetKubeconfigResponse, error)
	GetClusterVars(ctx context.Context, in *GetClusterVarsRequest, opts ...grpc.CallOption) (*GetClusterVarsResponse, error)
	GetCloudFileSecret(ctx context.Context, in *GetCloudFileSecretRequest, opts ...grpc.CallOption) (*GetCloudFileSecretResponse, error)
	CreateCloudSecret(ctx context.Context, in *CreateCloudSecretRequest, opts ...grpc.CallOption) (*CreateCloudSecretResponse, error)
	DeleteCloudSecret(ctx context.Context, in *DeleteCloudSecretRequest, opts ...grpc.CallOption) (*DeleteCloudSecretResponse, error)
	GetCloudSecret(ctx context.Context, in *GetCloudSecretRequest, opts ...grpc.CallOption) (*GetCloudSecretResponse, error)
	GetCloudSecrets(ctx context.Context, in *GetCloudSecretsRequest, opts ...grpc.CallOption) (*GetCloudSecretsResponse, error)
	GetCephAccess(ctx context.Context, in *GetCephAccessRequest, opts ...grpc.CallOption) (*GetCephAccessResponse, error)
	GetSshKey(ctx context.Context, in *GetSshKeyRequest, opts ...grpc.CallOption) (*GetSshKeyResponse, error)
	GetProxmoxApi(ctx context.Context, in *GetProxmoxApiRequest, opts ...grpc.CallOption) (*GetProxmoxApiResponse, error)
	CreateProxmoxApi(ctx context.Context, in *CreateProxmoxApiRequest, opts ...grpc.CallOption) (*CreateProxmoxApiResponse, error)
	DeleteProxmoxApi(ctx context.Context, in *DeleteProxmoxApiRequest, opts ...grpc.CallOption) (*DeleteProxmoxApiResponse, error)
	GetProxmoxHost(ctx context.Context, in *GetProxmoxHostRequest, opts ...grpc.CallOption) (*GetProxmoxHostResponse, error)
	GetPveInventory(ctx context.Context, in *GetPveInventoryRequest, opts ...grpc.CallOption) (*GetPveInventoryResponse, error)
	GetVmVarsBlake(ctx context.Context, in *GetVmVarsBlakeRequest, opts ...grpc.CallOption) (*GetVmVarsBlakeResponse, error)
}

type cloudServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudServiceClient(cc grpc.ClientConnInterface) CloudServiceClient {
	return &cloudServiceClient{cc}
}

func (c *cloudServiceClient) GetMasterKubeconfig(ctx context.Context, in *GetKubeconfigRequest, opts ...grpc.CallOption) (*GetKubeconfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKubeconfigResponse)
	err := c.cc.Invoke(ctx, CloudService_GetMasterKubeconfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudServiceClient) GetClusterVars(ctx context.Context, in *GetClusterVarsRequest, opts ...grpc.CallOption) (*GetClusterVarsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterVarsResponse)
	err := c.cc.Invoke(ctx, CloudService_GetClusterVars_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudServiceClient) GetCloudFileSecret(ctx context.Context, in *GetCloudFileSecretRequest, opts ...grpc.CallOption) (*GetCloudFileSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCloudFileSecretResponse)
	err := c.cc.Invoke(ctx, CloudService_GetCloudFileSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudServiceClient) CreateCloudSecret(ctx context.Context, in *CreateCloudSecretRequest, opts ...grpc.CallOption) (*CreateCloudSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCloudSecretResponse)
	err := c.cc.Invoke(ctx, CloudService_CreateCloudSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudServiceClient) DeleteCloudSecret(ctx context.Context, in *DeleteCloudSecretRequest, opts ...grpc.CallOption) (*DeleteCloudSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCloudSecretResponse)
	err := c.cc.Invoke(ctx, CloudService_DeleteCloudSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudServiceClient) GetCloudSecret(ctx context.Context, in *GetCloudSecretRequest, opts ...grpc.CallOption) (*GetCloudSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCloudSecretResponse)
	err := c.cc.Invoke(ctx, CloudService_GetCloudSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudServiceClient) GetCloudSecrets(ctx context.Context, in *GetCloudSecretsRequest, opts ...grpc.CallOption) (*GetCloudSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCloudSecretsResponse)
	err := c.cc.Invoke(ctx, CloudService_GetCloudSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudServiceClient) GetCephAccess(ctx context.Context, in *GetCephAccessRequest, opts ...grpc.CallOption) (*GetCephAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCephAccessResponse)
	err := c.cc.Invoke(ctx, CloudService_GetCephAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudServiceClient) GetSshKey(ctx context.Context, in *GetSshKeyRequest, opts ...grpc.CallOption) (*GetSshKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSshKeyResponse)
	err := c.cc.Invoke(ctx, CloudService_GetSshKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudServiceClient) GetProxmoxApi(ctx context.Context, in *GetProxmoxApiRequest, opts ...grpc.CallOption) (*GetProxmoxApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProxmoxApiResponse)
	err := c.cc.Invoke(ctx, CloudService_GetProxmoxApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudServiceClient) CreateProxmoxApi(ctx context.Context, in *CreateProxmoxApiRequest, opts ...grpc.CallOption) (*CreateProxmoxApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProxmoxApiResponse)
	err := c.cc.Invoke(ctx, CloudService_CreateProxmoxApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudServiceClient) DeleteProxmoxApi(ctx context.Context, in *DeleteProxmoxApiRequest, opts ...grpc.CallOption) (*DeleteProxmoxApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProxmoxApiResponse)
	err := c.cc.Invoke(ctx, CloudService_DeleteProxmoxApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudServiceClient) GetProxmoxHost(ctx context.Context, in *GetProxmoxHostRequest, opts ...grpc.CallOption) (*GetProxmoxHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProxmoxHostResponse)
	err := c.cc.Invoke(ctx, CloudService_GetProxmoxHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudServiceClient) GetPveInventory(ctx context.Context, in *GetPveInventoryRequest, opts ...grpc.CallOption) (*GetPveInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPveInventoryResponse)
	err := c.cc.Invoke(ctx, CloudService_GetPveInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudServiceClient) GetVmVarsBlake(ctx context.Context, in *GetVmVarsBlakeRequest, opts ...grpc.CallOption) (*GetVmVarsBlakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVmVarsBlakeResponse)
	err := c.cc.Invoke(ctx, CloudService_GetVmVarsBlake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudServiceServer is the server API for CloudService service.
// All implementations must embed UnimplementedCloudServiceServer
// for forward compatibility.
type CloudServiceServer interface {
	GetMasterKubeconfig(context.Context, *GetKubeconfigRequest) (*GetKubeconfigResponse, error)
	GetClusterVars(context.Context, *GetClusterVarsRequest) (*GetClusterVarsResponse, error)
	GetCloudFileSecret(context.Context, *GetCloudFileSecretRequest) (*GetCloudFileSecretResponse, error)
	CreateCloudSecret(context.Context, *CreateCloudSecretRequest) (*CreateCloudSecretResponse, error)
	DeleteCloudSecret(context.Context, *DeleteCloudSecretRequest) (*DeleteCloudSecretResponse, error)
	GetCloudSecret(context.Context, *GetCloudSecretRequest) (*GetCloudSecretResponse, error)
	GetCloudSecrets(context.Context, *GetCloudSecretsRequest) (*GetCloudSecretsResponse, error)
	GetCephAccess(context.Context, *GetCephAccessRequest) (*GetCephAccessResponse, error)
	GetSshKey(context.Context, *GetSshKeyRequest) (*GetSshKeyResponse, error)
	GetProxmoxApi(context.Context, *GetProxmoxApiRequest) (*GetProxmoxApiResponse, error)
	CreateProxmoxApi(context.Context, *CreateProxmoxApiRequest) (*CreateProxmoxApiResponse, error)
	DeleteProxmoxApi(context.Context, *DeleteProxmoxApiRequest) (*DeleteProxmoxApiResponse, error)
	GetProxmoxHost(context.Context, *GetProxmoxHostRequest) (*GetProxmoxHostResponse, error)
	GetPveInventory(context.Context, *GetPveInventoryRequest) (*GetPveInventoryResponse, error)
	GetVmVarsBlake(context.Context, *GetVmVarsBlakeRequest) (*GetVmVarsBlakeResponse, error)
	mustEmbedUnimplementedCloudServiceServer()
}

// UnimplementedCloudServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCloudServiceServer struct{}

func (UnimplementedCloudServiceServer) GetMasterKubeconfig(context.Context, *GetKubeconfigRequest) (*GetKubeconfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMasterKubeconfig not implemented")
}
func (UnimplementedCloudServiceServer) GetClusterVars(context.Context, *GetClusterVarsRequest) (*GetClusterVarsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterVars not implemented")
}
func (UnimplementedCloudServiceServer) GetCloudFileSecret(context.Context, *GetCloudFileSecretRequest) (*GetCloudFileSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCloudFileSecret not implemented")
}
func (UnimplementedCloudServiceServer) CreateCloudSecret(context.Context, *CreateCloudSecretRequest) (*CreateCloudSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCloudSecret not implemented")
}
func (UnimplementedCloudServiceServer) DeleteCloudSecret(context.Context, *DeleteCloudSecretRequest) (*DeleteCloudSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCloudSecret not implemented")
}
func (UnimplementedCloudServiceServer) GetCloudSecret(context.Context, *GetCloudSecretRequest) (*GetCloudSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCloudSecret not implemented")
}
func (UnimplementedCloudServiceServer) GetCloudSecrets(context.Context, *GetCloudSecretsRequest) (*GetCloudSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCloudSecrets not implemented")
}
func (UnimplementedCloudServiceServer) GetCephAccess(context.Context, *GetCephAccessRequest) (*GetCephAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCephAccess not implemented")
}
func (UnimplementedCloudServiceServer) GetSshKey(context.Context, *GetSshKeyRequest) (*GetSshKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSshKey not implemented")
}
func (UnimplementedCloudServiceServer) GetProxmoxApi(context.Context, *GetProxmoxApiRequest) (*GetProxmoxApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProxmoxApi not implemented")
}
func (UnimplementedCloudServiceServer) CreateProxmoxApi(context.Context, *CreateProxmoxApiRequest) (*CreateProxmoxApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProxmoxApi not implemented")
}
func (UnimplementedCloudServiceServer) DeleteProxmoxApi(context.Context, *DeleteProxmoxApiRequest) (*DeleteProxmoxApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProxmoxApi not implemented")
}
func (UnimplementedCloudServiceServer) GetProxmoxHost(context.Context, *GetProxmoxHostRequest) (*GetProxmoxHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProxmoxHost not implemented")
}
func (UnimplementedCloudServiceServer) GetPveInventory(context.Context, *GetPveInventoryRequest) (*GetPveInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPveInventory not implemented")
}
func (UnimplementedCloudServiceServer) GetVmVarsBlake(context.Context, *GetVmVarsBlakeRequest) (*GetVmVarsBlakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVmVarsBlake not implemented")
}
func (UnimplementedCloudServiceServer) mustEmbedUnimplementedCloudServiceServer() {}
func (UnimplementedCloudServiceServer) testEmbeddedByValue()                      {}

// UnsafeCloudServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudServiceServer will
// result in compilation errors.
type UnsafeCloudServiceServer interface {
	mustEmbedUnimplementedCloudServiceServer()
}

func RegisterCloudServiceServer(s grpc.ServiceRegistrar, srv CloudServiceServer) {
	// If the following call panics, it indicates UnimplementedCloudServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CloudService_ServiceDesc, srv)
}

func _CloudService_GetMasterKubeconfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKubeconfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudServiceServer).GetMasterKubeconfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudService_GetMasterKubeconfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudServiceServer).GetMasterKubeconfig(ctx, req.(*GetKubeconfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudService_GetClusterVars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterVarsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudServiceServer).GetClusterVars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudService_GetClusterVars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudServiceServer).GetClusterVars(ctx, req.(*GetClusterVarsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudService_GetCloudFileSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCloudFileSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudServiceServer).GetCloudFileSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudService_GetCloudFileSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudServiceServer).GetCloudFileSecret(ctx, req.(*GetCloudFileSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudService_CreateCloudSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCloudSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudServiceServer).CreateCloudSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudService_CreateCloudSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudServiceServer).CreateCloudSecret(ctx, req.(*CreateCloudSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudService_DeleteCloudSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCloudSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudServiceServer).DeleteCloudSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudService_DeleteCloudSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudServiceServer).DeleteCloudSecret(ctx, req.(*DeleteCloudSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudService_GetCloudSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCloudSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudServiceServer).GetCloudSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudService_GetCloudSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudServiceServer).GetCloudSecret(ctx, req.(*GetCloudSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudService_GetCloudSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCloudSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudServiceServer).GetCloudSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudService_GetCloudSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudServiceServer).GetCloudSecrets(ctx, req.(*GetCloudSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudService_GetCephAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCephAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudServiceServer).GetCephAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudService_GetCephAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudServiceServer).GetCephAccess(ctx, req.(*GetCephAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudService_GetSshKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSshKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudServiceServer).GetSshKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudService_GetSshKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudServiceServer).GetSshKey(ctx, req.(*GetSshKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudService_GetProxmoxApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProxmoxApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudServiceServer).GetProxmoxApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudService_GetProxmoxApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudServiceServer).GetProxmoxApi(ctx, req.(*GetProxmoxApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudService_CreateProxmoxApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProxmoxApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudServiceServer).CreateProxmoxApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudService_CreateProxmoxApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudServiceServer).CreateProxmoxApi(ctx, req.(*CreateProxmoxApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudService_DeleteProxmoxApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProxmoxApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudServiceServer).DeleteProxmoxApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudService_DeleteProxmoxApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudServiceServer).DeleteProxmoxApi(ctx, req.(*DeleteProxmoxApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudService_GetProxmoxHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProxmoxHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudServiceServer).GetProxmoxHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudService_GetProxmoxHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudServiceServer).GetProxmoxHost(ctx, req.(*GetProxmoxHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudService_GetPveInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPveInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudServiceServer).GetPveInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudService_GetPveInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudServiceServer).GetPveInventory(ctx, req.(*GetPveInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudService_GetVmVarsBlake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVmVarsBlakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudServiceServer).GetVmVarsBlake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudService_GetVmVarsBlake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudServiceServer).GetVmVarsBlake(ctx, req.(*GetVmVarsBlakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudService_ServiceDesc is the grpc.ServiceDesc for CloudService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.CloudService",
	HandlerType: (*CloudServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMasterKubeconfig",
			Handler:    _CloudService_GetMasterKubeconfig_Handler,
		},
		{
			MethodName: "GetClusterVars",
			Handler:    _CloudService_GetClusterVars_Handler,
		},
		{
			MethodName: "GetCloudFileSecret",
			Handler:    _CloudService_GetCloudFileSecret_Handler,
		},
		{
			MethodName: "CreateCloudSecret",
			Handler:    _CloudService_CreateCloudSecret_Handler,
		},
		{
			MethodName: "DeleteCloudSecret",
			Handler:    _CloudService_DeleteCloudSecret_Handler,
		},
		{
			MethodName: "GetCloudSecret",
			Handler:    _CloudService_GetCloudSecret_Handler,
		},
		{
			MethodName: "GetCloudSecrets",
			Handler:    _CloudService_GetCloudSecrets_Handler,
		},
		{
			MethodName: "GetCephAccess",
			Handler:    _CloudService_GetCephAccess_Handler,
		},
		{
			MethodName: "GetSshKey",
			Handler:    _CloudService_GetSshKey_Handler,
		},
		{
			MethodName: "GetProxmoxApi",
			Handler:    _CloudService_GetProxmoxApi_Handler,
		},
		{
			MethodName: "CreateProxmoxApi",
			Handler:    _CloudService_CreateProxmoxApi_Handler,
		},
		{
			MethodName: "DeleteProxmoxApi",
			Handler:    _CloudService_DeleteProxmoxApi_Handler,
		},
		{
			MethodName: "GetProxmoxHost",
			Handler:    _CloudService_GetProxmoxHost_Handler,
		},
		{
			MethodName: "GetPveInventory",
			Handler:    _CloudService_GetPveInventory_Handler,
		},
		{
			MethodName: "GetVmVarsBlake",
			Handler:    _CloudService_GetVmVarsBlake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/cloud.proto",
}
