// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protos/cloud.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSshKeyRequest_KeyType int32

const (
	GetSshKeyRequest_AUTOMATION   GetSshKeyRequest_KeyType = 0
	GetSshKeyRequest_PVE_HOST_RSA GetSshKeyRequest_KeyType = 1
)

// Enum value maps for GetSshKeyRequest_KeyType.
var (
	GetSshKeyRequest_KeyType_name = map[int32]string{
		0: "AUTOMATION",
		1: "PVE_HOST_RSA",
	}
	GetSshKeyRequest_KeyType_value = map[string]int32{
		"AUTOMATION":   0,
		"PVE_HOST_RSA": 1,
	}
)

func (x GetSshKeyRequest_KeyType) Enum() *GetSshKeyRequest_KeyType {
	p := new(GetSshKeyRequest_KeyType)
	*p = x
	return p
}

func (x GetSshKeyRequest_KeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetSshKeyRequest_KeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_cloud_proto_enumTypes[0].Descriptor()
}

func (GetSshKeyRequest_KeyType) Type() protoreflect.EnumType {
	return &file_protos_cloud_proto_enumTypes[0]
}

func (x GetSshKeyRequest_KeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetSshKeyRequest_KeyType.Descriptor instead.
func (GetSshKeyRequest_KeyType) EnumDescriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{10, 0}
}

type GetPveInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPve     string                 `protobuf:"bytes,1,opt,name=target_pve,json=targetPve,proto3" json:"target_pve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPveInventoryRequest) Reset() {
	*x = GetPveInventoryRequest{}
	mi := &file_protos_cloud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPveInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPveInventoryRequest) ProtoMessage() {}

func (x *GetPveInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPveInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetPveInventoryRequest) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{0}
}

func (x *GetPveInventoryRequest) GetTargetPve() string {
	if x != nil {
		return x.TargetPve
	}
	return ""
}

type GetPveInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     string                 `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	CloudDomain   string                 `protobuf:"bytes,2,opt,name=cloud_domain,json=cloudDomain,proto3" json:"cloud_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPveInventoryResponse) Reset() {
	*x = GetPveInventoryResponse{}
	mi := &file_protos_cloud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPveInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPveInventoryResponse) ProtoMessage() {}

func (x *GetPveInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPveInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetPveInventoryResponse) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{1}
}

func (x *GetPveInventoryResponse) GetInventory() string {
	if x != nil {
		return x.Inventory
	}
	return ""
}

func (x *GetPveInventoryResponse) GetCloudDomain() string {
	if x != nil {
		return x.CloudDomain
	}
	return ""
}

type GetProxmoxHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPve     string                 `protobuf:"bytes,1,opt,name=target_pve,json=targetPve,proto3" json:"target_pve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxmoxHostRequest) Reset() {
	*x = GetProxmoxHostRequest{}
	mi := &file_protos_cloud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxmoxHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxmoxHostRequest) ProtoMessage() {}

func (x *GetProxmoxHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxmoxHostRequest.ProtoReflect.Descriptor instead.
func (*GetProxmoxHostRequest) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{2}
}

func (x *GetProxmoxHostRequest) GetTargetPve() string {
	if x != nil {
		return x.TargetPve
	}
	return ""
}

type GetProxmoxHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PveHost       string                 `protobuf:"bytes,1,opt,name=pve_host,json=pveHost,proto3" json:"pve_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxmoxHostResponse) Reset() {
	*x = GetProxmoxHostResponse{}
	mi := &file_protos_cloud_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxmoxHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxmoxHostResponse) ProtoMessage() {}

func (x *GetProxmoxHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxmoxHostResponse.ProtoReflect.Descriptor instead.
func (*GetProxmoxHostResponse) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{3}
}

func (x *GetProxmoxHostResponse) GetPveHost() string {
	if x != nil {
		return x.PveHost
	}
	return ""
}

type GetProxmoxApiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPve     string                 `protobuf:"bytes,1,opt,name=target_pve,json=targetPve,proto3" json:"target_pve,omitempty"`
	ApiPath       string                 `protobuf:"bytes,2,opt,name=api_path,json=apiPath,proto3" json:"api_path,omitempty"`
	GetArgs       map[string]string      `protobuf:"bytes,3,rep,name=get_args,json=getArgs,proto3" json:"get_args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxmoxApiRequest) Reset() {
	*x = GetProxmoxApiRequest{}
	mi := &file_protos_cloud_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxmoxApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxmoxApiRequest) ProtoMessage() {}

func (x *GetProxmoxApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxmoxApiRequest.ProtoReflect.Descriptor instead.
func (*GetProxmoxApiRequest) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{4}
}

func (x *GetProxmoxApiRequest) GetTargetPve() string {
	if x != nil {
		return x.TargetPve
	}
	return ""
}

func (x *GetProxmoxApiRequest) GetApiPath() string {
	if x != nil {
		return x.ApiPath
	}
	return ""
}

func (x *GetProxmoxApiRequest) GetGetArgs() map[string]string {
	if x != nil {
		return x.GetArgs
	}
	return nil
}

type GetProxmoxApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonResp      string                 `protobuf:"bytes,1,opt,name=json_resp,json=jsonResp,proto3" json:"json_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxmoxApiResponse) Reset() {
	*x = GetProxmoxApiResponse{}
	mi := &file_protos_cloud_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxmoxApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxmoxApiResponse) ProtoMessage() {}

func (x *GetProxmoxApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxmoxApiResponse.ProtoReflect.Descriptor instead.
func (*GetProxmoxApiResponse) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{5}
}

func (x *GetProxmoxApiResponse) GetJsonResp() string {
	if x != nil {
		return x.JsonResp
	}
	return ""
}

type CreateProxmoxApiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPve     string                 `protobuf:"bytes,1,opt,name=target_pve,json=targetPve,proto3" json:"target_pve,omitempty"`
	ApiPath       string                 `protobuf:"bytes,2,opt,name=api_path,json=apiPath,proto3" json:"api_path,omitempty"`
	CreateArgs    map[string]string      `protobuf:"bytes,3,rep,name=create_args,json=createArgs,proto3" json:"create_args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProxmoxApiRequest) Reset() {
	*x = CreateProxmoxApiRequest{}
	mi := &file_protos_cloud_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProxmoxApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProxmoxApiRequest) ProtoMessage() {}

func (x *CreateProxmoxApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProxmoxApiRequest.ProtoReflect.Descriptor instead.
func (*CreateProxmoxApiRequest) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProxmoxApiRequest) GetTargetPve() string {
	if x != nil {
		return x.TargetPve
	}
	return ""
}

func (x *CreateProxmoxApiRequest) GetApiPath() string {
	if x != nil {
		return x.ApiPath
	}
	return ""
}

func (x *CreateProxmoxApiRequest) GetCreateArgs() map[string]string {
	if x != nil {
		return x.CreateArgs
	}
	return nil
}

type CreateProxmoxApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrMessage    string                 `protobuf:"bytes,2,opt,name=err_message,json=errMessage,proto3" json:"err_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProxmoxApiResponse) Reset() {
	*x = CreateProxmoxApiResponse{}
	mi := &file_protos_cloud_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProxmoxApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProxmoxApiResponse) ProtoMessage() {}

func (x *CreateProxmoxApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProxmoxApiResponse.ProtoReflect.Descriptor instead.
func (*CreateProxmoxApiResponse) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProxmoxApiResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateProxmoxApiResponse) GetErrMessage() string {
	if x != nil {
		return x.ErrMessage
	}
	return ""
}

type DeleteProxmoxApiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPve     string                 `protobuf:"bytes,1,opt,name=target_pve,json=targetPve,proto3" json:"target_pve,omitempty"`
	ApiPath       string                 `protobuf:"bytes,2,opt,name=api_path,json=apiPath,proto3" json:"api_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProxmoxApiRequest) Reset() {
	*x = DeleteProxmoxApiRequest{}
	mi := &file_protos_cloud_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProxmoxApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProxmoxApiRequest) ProtoMessage() {}

func (x *DeleteProxmoxApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProxmoxApiRequest.ProtoReflect.Descriptor instead.
func (*DeleteProxmoxApiRequest) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteProxmoxApiRequest) GetTargetPve() string {
	if x != nil {
		return x.TargetPve
	}
	return ""
}

func (x *DeleteProxmoxApiRequest) GetApiPath() string {
	if x != nil {
		return x.ApiPath
	}
	return ""
}

type DeleteProxmoxApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrMessage    string                 `protobuf:"bytes,2,opt,name=err_message,json=errMessage,proto3" json:"err_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProxmoxApiResponse) Reset() {
	*x = DeleteProxmoxApiResponse{}
	mi := &file_protos_cloud_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProxmoxApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProxmoxApiResponse) ProtoMessage() {}

func (x *DeleteProxmoxApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProxmoxApiResponse.ProtoReflect.Descriptor instead.
func (*DeleteProxmoxApiResponse) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProxmoxApiResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteProxmoxApiResponse) GetErrMessage() string {
	if x != nil {
		return x.ErrMessage
	}
	return ""
}

type GetSshKeyRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	TargetPve     string                   `protobuf:"bytes,1,opt,name=target_pve,json=targetPve,proto3" json:"target_pve,omitempty"`
	KeyType       GetSshKeyRequest_KeyType `protobuf:"varint,2,opt,name=key_type,json=keyType,proto3,enum=protos.GetSshKeyRequest_KeyType" json:"key_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSshKeyRequest) Reset() {
	*x = GetSshKeyRequest{}
	mi := &file_protos_cloud_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSshKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSshKeyRequest) ProtoMessage() {}

func (x *GetSshKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSshKeyRequest.ProtoReflect.Descriptor instead.
func (*GetSshKeyRequest) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{10}
}

func (x *GetSshKeyRequest) GetTargetPve() string {
	if x != nil {
		return x.TargetPve
	}
	return ""
}

func (x *GetSshKeyRequest) GetKeyType() GetSshKeyRequest_KeyType {
	if x != nil {
		return x.KeyType
	}
	return GetSshKeyRequest_AUTOMATION
}

type GetSshKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSshKeyResponse) Reset() {
	*x = GetSshKeyResponse{}
	mi := &file_protos_cloud_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSshKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSshKeyResponse) ProtoMessage() {}

func (x *GetSshKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSshKeyResponse.ProtoReflect.Descriptor instead.
func (*GetSshKeyResponse) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{11}
}

func (x *GetSshKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetCephAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPve     string                 `protobuf:"bytes,1,opt,name=target_pve,json=targetPve,proto3" json:"target_pve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCephAccessRequest) Reset() {
	*x = GetCephAccessRequest{}
	mi := &file_protos_cloud_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCephAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCephAccessRequest) ProtoMessage() {}

func (x *GetCephAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCephAccessRequest.ProtoReflect.Descriptor instead.
func (*GetCephAccessRequest) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{12}
}

func (x *GetCephAccessRequest) GetTargetPve() string {
	if x != nil {
		return x.TargetPve
	}
	return ""
}

type GetCephAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CephConf      string                 `protobuf:"bytes,1,opt,name=ceph_conf,json=cephConf,proto3" json:"ceph_conf,omitempty"`
	AdminKeyring  string                 `protobuf:"bytes,2,opt,name=admin_keyring,json=adminKeyring,proto3" json:"admin_keyring,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCephAccessResponse) Reset() {
	*x = GetCephAccessResponse{}
	mi := &file_protos_cloud_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCephAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCephAccessResponse) ProtoMessage() {}

func (x *GetCephAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCephAccessResponse.ProtoReflect.Descriptor instead.
func (*GetCephAccessResponse) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{13}
}

func (x *GetCephAccessResponse) GetCephConf() string {
	if x != nil {
		return x.CephConf
	}
	return ""
}

func (x *GetCephAccessResponse) GetAdminKeyring() string {
	if x != nil {
		return x.AdminKeyring
	}
	return ""
}

type GetKubeconfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPve     string                 `protobuf:"bytes,1,opt,name=target_pve,json=targetPve,proto3" json:"target_pve,omitempty"`
	StackName     string                 `protobuf:"bytes,2,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKubeconfigRequest) Reset() {
	*x = GetKubeconfigRequest{}
	mi := &file_protos_cloud_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKubeconfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKubeconfigRequest) ProtoMessage() {}

func (x *GetKubeconfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKubeconfigRequest.ProtoReflect.Descriptor instead.
func (*GetKubeconfigRequest) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{14}
}

func (x *GetKubeconfigRequest) GetTargetPve() string {
	if x != nil {
		return x.TargetPve
	}
	return ""
}

func (x *GetKubeconfigRequest) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

type GetKubeconfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKubeconfigResponse) Reset() {
	*x = GetKubeconfigResponse{}
	mi := &file_protos_cloud_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKubeconfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKubeconfigResponse) ProtoMessage() {}

func (x *GetKubeconfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKubeconfigResponse.ProtoReflect.Descriptor instead.
func (*GetKubeconfigResponse) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{15}
}

func (x *GetKubeconfigResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type GetClusterVarsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPve     string                 `protobuf:"bytes,1,opt,name=target_pve,json=targetPve,proto3" json:"target_pve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterVarsRequest) Reset() {
	*x = GetClusterVarsRequest{}
	mi := &file_protos_cloud_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterVarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterVarsRequest) ProtoMessage() {}

func (x *GetClusterVarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterVarsRequest.ProtoReflect.Descriptor instead.
func (*GetClusterVarsRequest) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{16}
}

func (x *GetClusterVarsRequest) GetTargetPve() string {
	if x != nil {
		return x.TargetPve
	}
	return ""
}

type GetClusterVarsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vars          string                 `protobuf:"bytes,1,opt,name=vars,proto3" json:"vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterVarsResponse) Reset() {
	*x = GetClusterVarsResponse{}
	mi := &file_protos_cloud_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterVarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterVarsResponse) ProtoMessage() {}

func (x *GetClusterVarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterVarsResponse.ProtoReflect.Descriptor instead.
func (*GetClusterVarsResponse) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{17}
}

func (x *GetClusterVarsResponse) GetVars() string {
	if x != nil {
		return x.Vars
	}
	return ""
}

type GetCloudFileSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPve     string                 `protobuf:"bytes,1,opt,name=target_pve,json=targetPve,proto3" json:"target_pve,omitempty"`
	SecretName    string                 `protobuf:"bytes,2,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	Rstrip        bool                   `protobuf:"varint,3,opt,name=rstrip,proto3" json:"rstrip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCloudFileSecretRequest) Reset() {
	*x = GetCloudFileSecretRequest{}
	mi := &file_protos_cloud_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCloudFileSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCloudFileSecretRequest) ProtoMessage() {}

func (x *GetCloudFileSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCloudFileSecretRequest.ProtoReflect.Descriptor instead.
func (*GetCloudFileSecretRequest) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{18}
}

func (x *GetCloudFileSecretRequest) GetTargetPve() string {
	if x != nil {
		return x.TargetPve
	}
	return ""
}

func (x *GetCloudFileSecretRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *GetCloudFileSecretRequest) GetRstrip() bool {
	if x != nil {
		return x.Rstrip
	}
	return false
}

type GetCloudFileSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCloudFileSecretResponse) Reset() {
	*x = GetCloudFileSecretResponse{}
	mi := &file_protos_cloud_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCloudFileSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCloudFileSecretResponse) ProtoMessage() {}

func (x *GetCloudFileSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCloudFileSecretResponse.ProtoReflect.Descriptor instead.
func (*GetCloudFileSecretResponse) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{19}
}

func (x *GetCloudFileSecretResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type CreateCloudSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CloudDomain   string                 `protobuf:"bytes,1,opt,name=cloud_domain,json=cloudDomain,proto3" json:"cloud_domain,omitempty"`
	TargetPve     string                 `protobuf:"bytes,2,opt,name=target_pve,json=targetPve,proto3" json:"target_pve,omitempty"`
	SecretName    string                 `protobuf:"bytes,3,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretData    string                 `protobuf:"bytes,4,opt,name=secret_data,json=secretData,proto3" json:"secret_data,omitempty"`
	SecretType    string                 `protobuf:"bytes,5,opt,name=secret_type,json=secretType,proto3" json:"secret_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCloudSecretRequest) Reset() {
	*x = CreateCloudSecretRequest{}
	mi := &file_protos_cloud_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCloudSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCloudSecretRequest) ProtoMessage() {}

func (x *CreateCloudSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCloudSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateCloudSecretRequest) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{20}
}

func (x *CreateCloudSecretRequest) GetCloudDomain() string {
	if x != nil {
		return x.CloudDomain
	}
	return ""
}

func (x *CreateCloudSecretRequest) GetTargetPve() string {
	if x != nil {
		return x.TargetPve
	}
	return ""
}

func (x *CreateCloudSecretRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *CreateCloudSecretRequest) GetSecretData() string {
	if x != nil {
		return x.SecretData
	}
	return ""
}

func (x *CreateCloudSecretRequest) GetSecretType() string {
	if x != nil {
		return x.SecretType
	}
	return ""
}

type CreateCloudSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrMessage    string                 `protobuf:"bytes,2,opt,name=err_message,json=errMessage,proto3" json:"err_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCloudSecretResponse) Reset() {
	*x = CreateCloudSecretResponse{}
	mi := &file_protos_cloud_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCloudSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCloudSecretResponse) ProtoMessage() {}

func (x *CreateCloudSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCloudSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateCloudSecretResponse) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{21}
}

func (x *CreateCloudSecretResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateCloudSecretResponse) GetErrMessage() string {
	if x != nil {
		return x.ErrMessage
	}
	return ""
}

type DeleteCloudSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CloudDomain   string                 `protobuf:"bytes,1,opt,name=cloud_domain,json=cloudDomain,proto3" json:"cloud_domain,omitempty"`
	TargetPve     string                 `protobuf:"bytes,2,opt,name=target_pve,json=targetPve,proto3" json:"target_pve,omitempty"`
	SecretName    string                 `protobuf:"bytes,3,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCloudSecretRequest) Reset() {
	*x = DeleteCloudSecretRequest{}
	mi := &file_protos_cloud_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCloudSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCloudSecretRequest) ProtoMessage() {}

func (x *DeleteCloudSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCloudSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteCloudSecretRequest) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteCloudSecretRequest) GetCloudDomain() string {
	if x != nil {
		return x.CloudDomain
	}
	return ""
}

func (x *DeleteCloudSecretRequest) GetTargetPve() string {
	if x != nil {
		return x.TargetPve
	}
	return ""
}

func (x *DeleteCloudSecretRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

type DeleteCloudSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrMessage    string                 `protobuf:"bytes,2,opt,name=err_message,json=errMessage,proto3" json:"err_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCloudSecretResponse) Reset() {
	*x = DeleteCloudSecretResponse{}
	mi := &file_protos_cloud_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCloudSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCloudSecretResponse) ProtoMessage() {}

func (x *DeleteCloudSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCloudSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteCloudSecretResponse) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteCloudSecretResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCloudSecretResponse) GetErrMessage() string {
	if x != nil {
		return x.ErrMessage
	}
	return ""
}

type GetCloudSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CloudDomain   string                 `protobuf:"bytes,1,opt,name=cloud_domain,json=cloudDomain,proto3" json:"cloud_domain,omitempty"`
	TargetPve     string                 `protobuf:"bytes,2,opt,name=target_pve,json=targetPve,proto3" json:"target_pve,omitempty"`
	SecretName    string                 `protobuf:"bytes,3,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCloudSecretRequest) Reset() {
	*x = GetCloudSecretRequest{}
	mi := &file_protos_cloud_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCloudSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCloudSecretRequest) ProtoMessage() {}

func (x *GetCloudSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCloudSecretRequest.ProtoReflect.Descriptor instead.
func (*GetCloudSecretRequest) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{24}
}

func (x *GetCloudSecretRequest) GetCloudDomain() string {
	if x != nil {
		return x.CloudDomain
	}
	return ""
}

func (x *GetCloudSecretRequest) GetTargetPve() string {
	if x != nil {
		return x.TargetPve
	}
	return ""
}

func (x *GetCloudSecretRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

type GetCloudSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCloudSecretResponse) Reset() {
	*x = GetCloudSecretResponse{}
	mi := &file_protos_cloud_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCloudSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCloudSecretResponse) ProtoMessage() {}

func (x *GetCloudSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCloudSecretResponse.ProtoReflect.Descriptor instead.
func (*GetCloudSecretResponse) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{25}
}

func (x *GetCloudSecretResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type GetCloudSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CloudDomain   string                 `protobuf:"bytes,1,opt,name=cloud_domain,json=cloudDomain,proto3" json:"cloud_domain,omitempty"`
	TargetPve     string                 `protobuf:"bytes,2,opt,name=target_pve,json=targetPve,proto3" json:"target_pve,omitempty"`
	SecretType    string                 `protobuf:"bytes,3,opt,name=secret_type,json=secretType,proto3" json:"secret_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCloudSecretsRequest) Reset() {
	*x = GetCloudSecretsRequest{}
	mi := &file_protos_cloud_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCloudSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCloudSecretsRequest) ProtoMessage() {}

func (x *GetCloudSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCloudSecretsRequest.ProtoReflect.Descriptor instead.
func (*GetCloudSecretsRequest) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{26}
}

func (x *GetCloudSecretsRequest) GetCloudDomain() string {
	if x != nil {
		return x.CloudDomain
	}
	return ""
}

func (x *GetCloudSecretsRequest) GetTargetPve() string {
	if x != nil {
		return x.TargetPve
	}
	return ""
}

func (x *GetCloudSecretsRequest) GetSecretType() string {
	if x != nil {
		return x.SecretType
	}
	return ""
}

type GetCloudSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       string                 `protobuf:"bytes,1,opt,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCloudSecretsResponse) Reset() {
	*x = GetCloudSecretsResponse{}
	mi := &file_protos_cloud_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCloudSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCloudSecretsResponse) ProtoMessage() {}

func (x *GetCloudSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCloudSecretsResponse.ProtoReflect.Descriptor instead.
func (*GetCloudSecretsResponse) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{27}
}

func (x *GetCloudSecretsResponse) GetSecrets() string {
	if x != nil {
		return x.Secrets
	}
	return ""
}

type GetVmVarsBlakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPve     string                 `protobuf:"bytes,1,opt,name=target_pve,json=targetPve,proto3" json:"target_pve,omitempty"`
	CloudDomain   string                 `protobuf:"bytes,2,opt,name=cloud_domain,json=cloudDomain,proto3" json:"cloud_domain,omitempty"`
	BlakeIds      []string               `protobuf:"bytes,3,rep,name=blake_ids,json=blakeIds,proto3" json:"blake_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmVarsBlakeRequest) Reset() {
	*x = GetVmVarsBlakeRequest{}
	mi := &file_protos_cloud_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmVarsBlakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmVarsBlakeRequest) ProtoMessage() {}

func (x *GetVmVarsBlakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmVarsBlakeRequest.ProtoReflect.Descriptor instead.
func (*GetVmVarsBlakeRequest) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{28}
}

func (x *GetVmVarsBlakeRequest) GetTargetPve() string {
	if x != nil {
		return x.TargetPve
	}
	return ""
}

func (x *GetVmVarsBlakeRequest) GetCloudDomain() string {
	if x != nil {
		return x.CloudDomain
	}
	return ""
}

func (x *GetVmVarsBlakeRequest) GetBlakeIds() []string {
	if x != nil {
		return x.BlakeIds
	}
	return nil
}

type GetVmVarsBlakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlakeIdVars   map[string]string      `protobuf:"bytes,1,rep,name=blake_id_vars,json=blakeIdVars,proto3" json:"blake_id_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmVarsBlakeResponse) Reset() {
	*x = GetVmVarsBlakeResponse{}
	mi := &file_protos_cloud_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmVarsBlakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmVarsBlakeResponse) ProtoMessage() {}

func (x *GetVmVarsBlakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmVarsBlakeResponse.ProtoReflect.Descriptor instead.
func (*GetVmVarsBlakeResponse) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{29}
}

func (x *GetVmVarsBlakeResponse) GetBlakeIdVars() map[string]string {
	if x != nil {
		return x.BlakeIdVars
	}
	return nil
}

type GetCloudDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPve     string                 `protobuf:"bytes,1,opt,name=target_pve,json=targetPve,proto3" json:"target_pve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCloudDomainRequest) Reset() {
	*x = GetCloudDomainRequest{}
	mi := &file_protos_cloud_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCloudDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCloudDomainRequest) ProtoMessage() {}

func (x *GetCloudDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCloudDomainRequest.ProtoReflect.Descriptor instead.
func (*GetCloudDomainRequest) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{30}
}

func (x *GetCloudDomainRequest) GetTargetPve() string {
	if x != nil {
		return x.TargetPve
	}
	return ""
}

type GetCloudDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCloudDomainResponse) Reset() {
	*x = GetCloudDomainResponse{}
	mi := &file_protos_cloud_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCloudDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCloudDomainResponse) ProtoMessage() {}

func (x *GetCloudDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cloud_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCloudDomainResponse.ProtoReflect.Descriptor instead.
func (*GetCloudDomainResponse) Descriptor() ([]byte, []int) {
	return file_protos_cloud_proto_rawDescGZIP(), []int{31}
}

func (x *GetCloudDomainResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

var File_protos_cloud_proto protoreflect.FileDescriptor

const file_protos_cloud_proto_rawDesc = "" +
	"\n" +
	"\x12protos/cloud.proto\x12\x06protos\"7\n" +
	"\x16GetPveInventoryRequest\x12\x1d\n" +
	"\n" +
	"target_pve\x18\x01 \x01(\tR\ttargetPve\"Z\n" +
	"\x17GetPveInventoryResponse\x12\x1c\n" +
	"\tinventory\x18\x01 \x01(\tR\tinventory\x12!\n" +
	"\fcloud_domain\x18\x02 \x01(\tR\vcloudDomain\"6\n" +
	"\x15GetProxmoxHostRequest\x12\x1d\n" +
	"\n" +
	"target_pve\x18\x01 \x01(\tR\ttargetPve\"3\n" +
	"\x16GetProxmoxHostResponse\x12\x19\n" +
	"\bpve_host\x18\x01 \x01(\tR\apveHost\"\xd2\x01\n" +
	"\x14GetProxmoxApiRequest\x12\x1d\n" +
	"\n" +
	"target_pve\x18\x01 \x01(\tR\ttargetPve\x12\x19\n" +
	"\bapi_path\x18\x02 \x01(\tR\aapiPath\x12D\n" +
	"\bget_args\x18\x03 \x03(\v2).protos.GetProxmoxApiRequest.GetArgsEntryR\agetArgs\x1a:\n" +
	"\fGetArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x15GetProxmoxApiResponse\x12\x1b\n" +
	"\tjson_resp\x18\x01 \x01(\tR\bjsonResp\"\xe4\x01\n" +
	"\x17CreateProxmoxApiRequest\x12\x1d\n" +
	"\n" +
	"target_pve\x18\x01 \x01(\tR\ttargetPve\x12\x19\n" +
	"\bapi_path\x18\x02 \x01(\tR\aapiPath\x12P\n" +
	"\vcreate_args\x18\x03 \x03(\v2/.protos.CreateProxmoxApiRequest.CreateArgsEntryR\n" +
	"createArgs\x1a=\n" +
	"\x0fCreateArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x18CreateProxmoxApiResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\verr_message\x18\x02 \x01(\tR\n" +
	"errMessage\"S\n" +
	"\x17DeleteProxmoxApiRequest\x12\x1d\n" +
	"\n" +
	"target_pve\x18\x01 \x01(\tR\ttargetPve\x12\x19\n" +
	"\bapi_path\x18\x02 \x01(\tR\aapiPath\"U\n" +
	"\x18DeleteProxmoxApiResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\verr_message\x18\x02 \x01(\tR\n" +
	"errMessage\"\x9b\x01\n" +
	"\x10GetSshKeyRequest\x12\x1d\n" +
	"\n" +
	"target_pve\x18\x01 \x01(\tR\ttargetPve\x12;\n" +
	"\bkey_type\x18\x02 \x01(\x0e2 .protos.GetSshKeyRequest.KeyTypeR\akeyType\"+\n" +
	"\aKeyType\x12\x0e\n" +
	"\n" +
	"AUTOMATION\x10\x00\x12\x10\n" +
	"\fPVE_HOST_RSA\x10\x01\"%\n" +
	"\x11GetSshKeyResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"5\n" +
	"\x14GetCephAccessRequest\x12\x1d\n" +
	"\n" +
	"target_pve\x18\x01 \x01(\tR\ttargetPve\"Y\n" +
	"\x15GetCephAccessResponse\x12\x1b\n" +
	"\tceph_conf\x18\x01 \x01(\tR\bcephConf\x12#\n" +
	"\radmin_keyring\x18\x02 \x01(\tR\fadminKeyring\"T\n" +
	"\x14GetKubeconfigRequest\x12\x1d\n" +
	"\n" +
	"target_pve\x18\x01 \x01(\tR\ttargetPve\x12\x1d\n" +
	"\n" +
	"stack_name\x18\x02 \x01(\tR\tstackName\"/\n" +
	"\x15GetKubeconfigResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"6\n" +
	"\x15GetClusterVarsRequest\x12\x1d\n" +
	"\n" +
	"target_pve\x18\x01 \x01(\tR\ttargetPve\",\n" +
	"\x16GetClusterVarsResponse\x12\x12\n" +
	"\x04vars\x18\x01 \x01(\tR\x04vars\"s\n" +
	"\x19GetCloudFileSecretRequest\x12\x1d\n" +
	"\n" +
	"target_pve\x18\x01 \x01(\tR\ttargetPve\x12\x1f\n" +
	"\vsecret_name\x18\x02 \x01(\tR\n" +
	"secretName\x12\x16\n" +
	"\x06rstrip\x18\x03 \x01(\bR\x06rstrip\"4\n" +
	"\x1aGetCloudFileSecretResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\"\xbf\x01\n" +
	"\x18CreateCloudSecretRequest\x12!\n" +
	"\fcloud_domain\x18\x01 \x01(\tR\vcloudDomain\x12\x1d\n" +
	"\n" +
	"target_pve\x18\x02 \x01(\tR\ttargetPve\x12\x1f\n" +
	"\vsecret_name\x18\x03 \x01(\tR\n" +
	"secretName\x12\x1f\n" +
	"\vsecret_data\x18\x04 \x01(\tR\n" +
	"secretData\x12\x1f\n" +
	"\vsecret_type\x18\x05 \x01(\tR\n" +
	"secretType\"V\n" +
	"\x19CreateCloudSecretResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\verr_message\x18\x02 \x01(\tR\n" +
	"errMessage\"}\n" +
	"\x18DeleteCloudSecretRequest\x12!\n" +
	"\fcloud_domain\x18\x01 \x01(\tR\vcloudDomain\x12\x1d\n" +
	"\n" +
	"target_pve\x18\x02 \x01(\tR\ttargetPve\x12\x1f\n" +
	"\vsecret_name\x18\x03 \x01(\tR\n" +
	"secretName\"V\n" +
	"\x19DeleteCloudSecretResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\verr_message\x18\x02 \x01(\tR\n" +
	"errMessage\"z\n" +
	"\x15GetCloudSecretRequest\x12!\n" +
	"\fcloud_domain\x18\x01 \x01(\tR\vcloudDomain\x12\x1d\n" +
	"\n" +
	"target_pve\x18\x02 \x01(\tR\ttargetPve\x12\x1f\n" +
	"\vsecret_name\x18\x03 \x01(\tR\n" +
	"secretName\"0\n" +
	"\x16GetCloudSecretResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\"{\n" +
	"\x16GetCloudSecretsRequest\x12!\n" +
	"\fcloud_domain\x18\x01 \x01(\tR\vcloudDomain\x12\x1d\n" +
	"\n" +
	"target_pve\x18\x02 \x01(\tR\ttargetPve\x12\x1f\n" +
	"\vsecret_type\x18\x03 \x01(\tR\n" +
	"secretType\"3\n" +
	"\x17GetCloudSecretsResponse\x12\x18\n" +
	"\asecrets\x18\x01 \x01(\tR\asecrets\"v\n" +
	"\x15GetVmVarsBlakeRequest\x12\x1d\n" +
	"\n" +
	"target_pve\x18\x01 \x01(\tR\ttargetPve\x12!\n" +
	"\fcloud_domain\x18\x02 \x01(\tR\vcloudDomain\x12\x1b\n" +
	"\tblake_ids\x18\x03 \x03(\tR\bblakeIds\"\xad\x01\n" +
	"\x16GetVmVarsBlakeResponse\x12S\n" +
	"\rblake_id_vars\x18\x01 \x03(\v2/.protos.GetVmVarsBlakeResponse.BlakeIdVarsEntryR\vblakeIdVars\x1a>\n" +
	"\x10BlakeIdVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"6\n" +
	"\x15GetCloudDomainRequest\x12\x1d\n" +
	"\n" +
	"target_pve\x18\x01 \x01(\tR\ttargetPve\"0\n" +
	"\x16GetCloudDomainResponse\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain2\xbc\n" +
	"\n" +
	"\fCloudService\x12R\n" +
	"\x13GetMasterKubeconfig\x12\x1c.protos.GetKubeconfigRequest\x1a\x1d.protos.GetKubeconfigResponse\x12O\n" +
	"\x0eGetClusterVars\x12\x1d.protos.GetClusterVarsRequest\x1a\x1e.protos.GetClusterVarsResponse\x12[\n" +
	"\x12GetCloudFileSecret\x12!.protos.GetCloudFileSecretRequest\x1a\".protos.GetCloudFileSecretResponse\x12X\n" +
	"\x11CreateCloudSecret\x12 .protos.CreateCloudSecretRequest\x1a!.protos.CreateCloudSecretResponse\x12X\n" +
	"\x11DeleteCloudSecret\x12 .protos.DeleteCloudSecretRequest\x1a!.protos.DeleteCloudSecretResponse\x12O\n" +
	"\x0eGetCloudSecret\x12\x1d.protos.GetCloudSecretRequest\x1a\x1e.protos.GetCloudSecretResponse\x12R\n" +
	"\x0fGetCloudSecrets\x12\x1e.protos.GetCloudSecretsRequest\x1a\x1f.protos.GetCloudSecretsResponse\x12L\n" +
	"\rGetCephAccess\x12\x1c.protos.GetCephAccessRequest\x1a\x1d.protos.GetCephAccessResponse\x12@\n" +
	"\tGetSshKey\x12\x18.protos.GetSshKeyRequest\x1a\x19.protos.GetSshKeyResponse\x12L\n" +
	"\rGetProxmoxApi\x12\x1c.protos.GetProxmoxApiRequest\x1a\x1d.protos.GetProxmoxApiResponse\x12U\n" +
	"\x10CreateProxmoxApi\x12\x1f.protos.CreateProxmoxApiRequest\x1a .protos.CreateProxmoxApiResponse\x12U\n" +
	"\x10DeleteProxmoxApi\x12\x1f.protos.DeleteProxmoxApiRequest\x1a .protos.DeleteProxmoxApiResponse\x12O\n" +
	"\x0eGetProxmoxHost\x12\x1d.protos.GetProxmoxHostRequest\x1a\x1e.protos.GetProxmoxHostResponse\x12R\n" +
	"\x0fGetPveInventory\x12\x1e.protos.GetPveInventoryRequest\x1a\x1f.protos.GetPveInventoryResponse\x12O\n" +
	"\x0eGetCloudDomain\x12\x1d.protos.GetCloudDomainRequest\x1a\x1e.protos.GetCloudDomainResponse\x12O\n" +
	"\x0eGetVmVarsBlake\x12\x1d.protos.GetVmVarsBlakeRequest\x1a\x1e.protos.GetVmVarsBlakeResponseBQZOgithub.com/Proxmox-Cloud/terraform-provider-pxc/internal/provider/protos;protosb\x06proto3"

var (
	file_protos_cloud_proto_rawDescOnce sync.Once
	file_protos_cloud_proto_rawDescData []byte
)

func file_protos_cloud_proto_rawDescGZIP() []byte {
	file_protos_cloud_proto_rawDescOnce.Do(func() {
		file_protos_cloud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_cloud_proto_rawDesc), len(file_protos_cloud_proto_rawDesc)))
	})
	return file_protos_cloud_proto_rawDescData
}

var file_protos_cloud_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_cloud_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_protos_cloud_proto_goTypes = []any{
	(GetSshKeyRequest_KeyType)(0),      // 0: protos.GetSshKeyRequest.KeyType
	(*GetPveInventoryRequest)(nil),     // 1: protos.GetPveInventoryRequest
	(*GetPveInventoryResponse)(nil),    // 2: protos.GetPveInventoryResponse
	(*GetProxmoxHostRequest)(nil),      // 3: protos.GetProxmoxHostRequest
	(*GetProxmoxHostResponse)(nil),     // 4: protos.GetProxmoxHostResponse
	(*GetProxmoxApiRequest)(nil),       // 5: protos.GetProxmoxApiRequest
	(*GetProxmoxApiResponse)(nil),      // 6: protos.GetProxmoxApiResponse
	(*CreateProxmoxApiRequest)(nil),    // 7: protos.CreateProxmoxApiRequest
	(*CreateProxmoxApiResponse)(nil),   // 8: protos.CreateProxmoxApiResponse
	(*DeleteProxmoxApiRequest)(nil),    // 9: protos.DeleteProxmoxApiRequest
	(*DeleteProxmoxApiResponse)(nil),   // 10: protos.DeleteProxmoxApiResponse
	(*GetSshKeyRequest)(nil),           // 11: protos.GetSshKeyRequest
	(*GetSshKeyResponse)(nil),          // 12: protos.GetSshKeyResponse
	(*GetCephAccessRequest)(nil),       // 13: protos.GetCephAccessRequest
	(*GetCephAccessResponse)(nil),      // 14: protos.GetCephAccessResponse
	(*GetKubeconfigRequest)(nil),       // 15: protos.GetKubeconfigRequest
	(*GetKubeconfigResponse)(nil),      // 16: protos.GetKubeconfigResponse
	(*GetClusterVarsRequest)(nil),      // 17: protos.GetClusterVarsRequest
	(*GetClusterVarsResponse)(nil),     // 18: protos.GetClusterVarsResponse
	(*GetCloudFileSecretRequest)(nil),  // 19: protos.GetCloudFileSecretRequest
	(*GetCloudFileSecretResponse)(nil), // 20: protos.GetCloudFileSecretResponse
	(*CreateCloudSecretRequest)(nil),   // 21: protos.CreateCloudSecretRequest
	(*CreateCloudSecretResponse)(nil),  // 22: protos.CreateCloudSecretResponse
	(*DeleteCloudSecretRequest)(nil),   // 23: protos.DeleteCloudSecretRequest
	(*DeleteCloudSecretResponse)(nil),  // 24: protos.DeleteCloudSecretResponse
	(*GetCloudSecretRequest)(nil),      // 25: protos.GetCloudSecretRequest
	(*GetCloudSecretResponse)(nil),     // 26: protos.GetCloudSecretResponse
	(*GetCloudSecretsRequest)(nil),     // 27: protos.GetCloudSecretsRequest
	(*GetCloudSecretsResponse)(nil),    // 28: protos.GetCloudSecretsResponse
	(*GetVmVarsBlakeRequest)(nil),      // 29: protos.GetVmVarsBlakeRequest
	(*GetVmVarsBlakeResponse)(nil),     // 30: protos.GetVmVarsBlakeResponse
	(*GetCloudDomainRequest)(nil),      // 31: protos.GetCloudDomainRequest
	(*GetCloudDomainResponse)(nil),     // 32: protos.GetCloudDomainResponse
	nil,                                // 33: protos.GetProxmoxApiRequest.GetArgsEntry
	nil,                                // 34: protos.CreateProxmoxApiRequest.CreateArgsEntry
	nil,                                // 35: protos.GetVmVarsBlakeResponse.BlakeIdVarsEntry
}
var file_protos_cloud_proto_depIdxs = []int32{
	33, // 0: protos.GetProxmoxApiRequest.get_args:type_name -> protos.GetProxmoxApiRequest.GetArgsEntry
	34, // 1: protos.CreateProxmoxApiRequest.create_args:type_name -> protos.CreateProxmoxApiRequest.CreateArgsEntry
	0,  // 2: protos.GetSshKeyRequest.key_type:type_name -> protos.GetSshKeyRequest.KeyType
	35, // 3: protos.GetVmVarsBlakeResponse.blake_id_vars:type_name -> protos.GetVmVarsBlakeResponse.BlakeIdVarsEntry
	15, // 4: protos.CloudService.GetMasterKubeconfig:input_type -> protos.GetKubeconfigRequest
	17, // 5: protos.CloudService.GetClusterVars:input_type -> protos.GetClusterVarsRequest
	19, // 6: protos.CloudService.GetCloudFileSecret:input_type -> protos.GetCloudFileSecretRequest
	21, // 7: protos.CloudService.CreateCloudSecret:input_type -> protos.CreateCloudSecretRequest
	23, // 8: protos.CloudService.DeleteCloudSecret:input_type -> protos.DeleteCloudSecretRequest
	25, // 9: protos.CloudService.GetCloudSecret:input_type -> protos.GetCloudSecretRequest
	27, // 10: protos.CloudService.GetCloudSecrets:input_type -> protos.GetCloudSecretsRequest
	13, // 11: protos.CloudService.GetCephAccess:input_type -> protos.GetCephAccessRequest
	11, // 12: protos.CloudService.GetSshKey:input_type -> protos.GetSshKeyRequest
	5,  // 13: protos.CloudService.GetProxmoxApi:input_type -> protos.GetProxmoxApiRequest
	7,  // 14: protos.CloudService.CreateProxmoxApi:input_type -> protos.CreateProxmoxApiRequest
	9,  // 15: protos.CloudService.DeleteProxmoxApi:input_type -> protos.DeleteProxmoxApiRequest
	3,  // 16: protos.CloudService.GetProxmoxHost:input_type -> protos.GetProxmoxHostRequest
	1,  // 17: protos.CloudService.GetPveInventory:input_type -> protos.GetPveInventoryRequest
	31, // 18: protos.CloudService.GetCloudDomain:input_type -> protos.GetCloudDomainRequest
	29, // 19: protos.CloudService.GetVmVarsBlake:input_type -> protos.GetVmVarsBlakeRequest
	16, // 20: protos.CloudService.GetMasterKubeconfig:output_type -> protos.GetKubeconfigResponse
	18, // 21: protos.CloudService.GetClusterVars:output_type -> protos.GetClusterVarsResponse
	20, // 22: protos.CloudService.GetCloudFileSecret:output_type -> protos.GetCloudFileSecretResponse
	22, // 23: protos.CloudService.CreateCloudSecret:output_type -> protos.CreateCloudSecretResponse
	24, // 24: protos.CloudService.DeleteCloudSecret:output_type -> protos.DeleteCloudSecretResponse
	26, // 25: protos.CloudService.GetCloudSecret:output_type -> protos.GetCloudSecretResponse
	28, // 26: protos.CloudService.GetCloudSecrets:output_type -> protos.GetCloudSecretsResponse
	14, // 27: protos.CloudService.GetCephAccess:output_type -> protos.GetCephAccessResponse
	12, // 28: protos.CloudService.GetSshKey:output_type -> protos.GetSshKeyResponse
	6,  // 29: protos.CloudService.GetProxmoxApi:output_type -> protos.GetProxmoxApiResponse
	8,  // 30: protos.CloudService.CreateProxmoxApi:output_type -> protos.CreateProxmoxApiResponse
	10, // 31: protos.CloudService.DeleteProxmoxApi:output_type -> protos.DeleteProxmoxApiResponse
	4,  // 32: protos.CloudService.GetProxmoxHost:output_type -> protos.GetProxmoxHostResponse
	2,  // 33: protos.CloudService.GetPveInventory:output_type -> protos.GetPveInventoryResponse
	32, // 34: protos.CloudService.GetCloudDomain:output_type -> protos.GetCloudDomainResponse
	30, // 35: protos.CloudService.GetVmVarsBlake:output_type -> protos.GetVmVarsBlakeResponse
	20, // [20:36] is the sub-list for method output_type
	4,  // [4:20] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_protos_cloud_proto_init() }
func file_protos_cloud_proto_init() {
	if File_protos_cloud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_cloud_proto_rawDesc), len(file_protos_cloud_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_cloud_proto_goTypes,
		DependencyIndexes: file_protos_cloud_proto_depIdxs,
		EnumInfos:         file_protos_cloud_proto_enumTypes,
		MessageInfos:      file_protos_cloud_proto_msgTypes,
	}.Build()
	File_protos_cloud_proto = out.File
	file_protos_cloud_proto_goTypes = nil
	file_protos_cloud_proto_depIdxs = nil
}
