# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pve_cloud_rpc.protos.cloud_pb2 as cloud__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloud_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CloudServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMasterKubeconfig = channel.unary_unary(
                '/protos.CloudService/GetMasterKubeconfig',
                request_serializer=cloud__pb2.GetKubeconfigRequest.SerializeToString,
                response_deserializer=cloud__pb2.GetKubeconfigResponse.FromString,
                _registered_method=True)
        self.GetClusterVars = channel.unary_unary(
                '/protos.CloudService/GetClusterVars',
                request_serializer=cloud__pb2.GetClusterVarsRequest.SerializeToString,
                response_deserializer=cloud__pb2.GetClusterVarsResponse.FromString,
                _registered_method=True)
        self.GetCloudFileSecret = channel.unary_unary(
                '/protos.CloudService/GetCloudFileSecret',
                request_serializer=cloud__pb2.GetCloudFileSecretRequest.SerializeToString,
                response_deserializer=cloud__pb2.GetCloudFileSecretResponse.FromString,
                _registered_method=True)
        self.CreateCloudSecret = channel.unary_unary(
                '/protos.CloudService/CreateCloudSecret',
                request_serializer=cloud__pb2.CreateCloudSecretRequest.SerializeToString,
                response_deserializer=cloud__pb2.CreateCloudSecretResponse.FromString,
                _registered_method=True)
        self.DeleteCloudSecret = channel.unary_unary(
                '/protos.CloudService/DeleteCloudSecret',
                request_serializer=cloud__pb2.DeleteCloudSecretRequest.SerializeToString,
                response_deserializer=cloud__pb2.DeleteCloudSecretResponse.FromString,
                _registered_method=True)
        self.GetCloudSecret = channel.unary_unary(
                '/protos.CloudService/GetCloudSecret',
                request_serializer=cloud__pb2.GetCloudSecretRequest.SerializeToString,
                response_deserializer=cloud__pb2.GetCloudSecretResponse.FromString,
                _registered_method=True)
        self.GetCloudSecrets = channel.unary_unary(
                '/protos.CloudService/GetCloudSecrets',
                request_serializer=cloud__pb2.GetCloudSecretsRequest.SerializeToString,
                response_deserializer=cloud__pb2.GetCloudSecretsResponse.FromString,
                _registered_method=True)
        self.GetCephAccess = channel.unary_unary(
                '/protos.CloudService/GetCephAccess',
                request_serializer=cloud__pb2.GetCephAccessRequest.SerializeToString,
                response_deserializer=cloud__pb2.GetCephAccessResponse.FromString,
                _registered_method=True)
        self.GetSshKey = channel.unary_unary(
                '/protos.CloudService/GetSshKey',
                request_serializer=cloud__pb2.GetSshKeyRequest.SerializeToString,
                response_deserializer=cloud__pb2.GetSshKeyResponse.FromString,
                _registered_method=True)
        self.GetProxmoxApi = channel.unary_unary(
                '/protos.CloudService/GetProxmoxApi',
                request_serializer=cloud__pb2.GetProxmoxApiRequest.SerializeToString,
                response_deserializer=cloud__pb2.GetProxmoxApiResponse.FromString,
                _registered_method=True)
        self.CreateProxmoxApi = channel.unary_unary(
                '/protos.CloudService/CreateProxmoxApi',
                request_serializer=cloud__pb2.CreateProxmoxApiRequest.SerializeToString,
                response_deserializer=cloud__pb2.CreateProxmoxApiResponse.FromString,
                _registered_method=True)
        self.DeleteProxmoxApi = channel.unary_unary(
                '/protos.CloudService/DeleteProxmoxApi',
                request_serializer=cloud__pb2.DeleteProxmoxApiRequest.SerializeToString,
                response_deserializer=cloud__pb2.DeleteProxmoxApiResponse.FromString,
                _registered_method=True)
        self.GetProxmoxHost = channel.unary_unary(
                '/protos.CloudService/GetProxmoxHost',
                request_serializer=cloud__pb2.GetProxmoxHostRequest.SerializeToString,
                response_deserializer=cloud__pb2.GetProxmoxHostResponse.FromString,
                _registered_method=True)
        self.GetPveInventory = channel.unary_unary(
                '/protos.CloudService/GetPveInventory',
                request_serializer=cloud__pb2.GetPveInventoryRequest.SerializeToString,
                response_deserializer=cloud__pb2.GetPveInventoryResponse.FromString,
                _registered_method=True)
        self.GetCloudDomain = channel.unary_unary(
                '/protos.CloudService/GetCloudDomain',
                request_serializer=cloud__pb2.GetCloudDomainRequest.SerializeToString,
                response_deserializer=cloud__pb2.GetCloudDomainResponse.FromString,
                _registered_method=True)
        self.GetVmVarsBlake = channel.unary_unary(
                '/protos.CloudService/GetVmVarsBlake',
                request_serializer=cloud__pb2.GetVmVarsBlakeRequest.SerializeToString,
                response_deserializer=cloud__pb2.GetVmVarsBlakeResponse.FromString,
                _registered_method=True)
        self.GetDnsARecordSet = channel.unary_unary(
                '/protos.CloudService/GetDnsARecordSet',
                request_serializer=cloud__pb2.GetDnsARecordSetRequest.SerializeToString,
                response_deserializer=cloud__pb2.GetDnsARecordSetResponse.FromString,
                _registered_method=True)
        self.CreateExternalAcmeTls = channel.unary_unary(
                '/protos.CloudService/CreateExternalAcmeTls',
                request_serializer=cloud__pb2.CreateExternalAcmeTlsRequest.SerializeToString,
                response_deserializer=cloud__pb2.ExternalAcmeTlsResponse.FromString,
                _registered_method=True)
        self.DeleteExternalAcmeTls = channel.unary_unary(
                '/protos.CloudService/DeleteExternalAcmeTls',
                request_serializer=cloud__pb2.DeleteExternalAcmeTlsRequest.SerializeToString,
                response_deserializer=cloud__pb2.ExternalAcmeTlsResponse.FromString,
                _registered_method=True)
        self.CreateCNameRecord = channel.unary_unary(
                '/protos.CloudService/CreateCNameRecord',
                request_serializer=cloud__pb2.CreateCNameRecordRequest.SerializeToString,
                response_deserializer=cloud__pb2.CNameRecordResponse.FromString,
                _registered_method=True)
        self.DeleteCNameRecord = channel.unary_unary(
                '/protos.CloudService/DeleteCNameRecord',
                request_serializer=cloud__pb2.DeleteCNameRecordRequest.SerializeToString,
                response_deserializer=cloud__pb2.CNameRecordResponse.FromString,
                _registered_method=True)
        self.GetK0sKubeconfig = channel.unary_unary(
                '/protos.CloudService/GetK0sKubeconfig',
                request_serializer=cloud__pb2.GetK0sKubeconfigRequest.SerializeToString,
                response_deserializer=cloud__pb2.GetKubeconfigResponse.FromString,
                _registered_method=True)


class CloudServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetMasterKubeconfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterVars(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCloudFileSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCloudSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCloudSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCloudSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCloudSecrets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCephAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSshKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProxmoxApi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProxmoxApi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProxmoxApi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProxmoxHost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPveInventory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCloudDomain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVmVarsBlake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDnsARecordSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateExternalAcmeTls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteExternalAcmeTls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCNameRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCNameRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetK0sKubeconfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMasterKubeconfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMasterKubeconfig,
                    request_deserializer=cloud__pb2.GetKubeconfigRequest.FromString,
                    response_serializer=cloud__pb2.GetKubeconfigResponse.SerializeToString,
            ),
            'GetClusterVars': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterVars,
                    request_deserializer=cloud__pb2.GetClusterVarsRequest.FromString,
                    response_serializer=cloud__pb2.GetClusterVarsResponse.SerializeToString,
            ),
            'GetCloudFileSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCloudFileSecret,
                    request_deserializer=cloud__pb2.GetCloudFileSecretRequest.FromString,
                    response_serializer=cloud__pb2.GetCloudFileSecretResponse.SerializeToString,
            ),
            'CreateCloudSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCloudSecret,
                    request_deserializer=cloud__pb2.CreateCloudSecretRequest.FromString,
                    response_serializer=cloud__pb2.CreateCloudSecretResponse.SerializeToString,
            ),
            'DeleteCloudSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCloudSecret,
                    request_deserializer=cloud__pb2.DeleteCloudSecretRequest.FromString,
                    response_serializer=cloud__pb2.DeleteCloudSecretResponse.SerializeToString,
            ),
            'GetCloudSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCloudSecret,
                    request_deserializer=cloud__pb2.GetCloudSecretRequest.FromString,
                    response_serializer=cloud__pb2.GetCloudSecretResponse.SerializeToString,
            ),
            'GetCloudSecrets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCloudSecrets,
                    request_deserializer=cloud__pb2.GetCloudSecretsRequest.FromString,
                    response_serializer=cloud__pb2.GetCloudSecretsResponse.SerializeToString,
            ),
            'GetCephAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCephAccess,
                    request_deserializer=cloud__pb2.GetCephAccessRequest.FromString,
                    response_serializer=cloud__pb2.GetCephAccessResponse.SerializeToString,
            ),
            'GetSshKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSshKey,
                    request_deserializer=cloud__pb2.GetSshKeyRequest.FromString,
                    response_serializer=cloud__pb2.GetSshKeyResponse.SerializeToString,
            ),
            'GetProxmoxApi': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProxmoxApi,
                    request_deserializer=cloud__pb2.GetProxmoxApiRequest.FromString,
                    response_serializer=cloud__pb2.GetProxmoxApiResponse.SerializeToString,
            ),
            'CreateProxmoxApi': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProxmoxApi,
                    request_deserializer=cloud__pb2.CreateProxmoxApiRequest.FromString,
                    response_serializer=cloud__pb2.CreateProxmoxApiResponse.SerializeToString,
            ),
            'DeleteProxmoxApi': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProxmoxApi,
                    request_deserializer=cloud__pb2.DeleteProxmoxApiRequest.FromString,
                    response_serializer=cloud__pb2.DeleteProxmoxApiResponse.SerializeToString,
            ),
            'GetProxmoxHost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProxmoxHost,
                    request_deserializer=cloud__pb2.GetProxmoxHostRequest.FromString,
                    response_serializer=cloud__pb2.GetProxmoxHostResponse.SerializeToString,
            ),
            'GetPveInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPveInventory,
                    request_deserializer=cloud__pb2.GetPveInventoryRequest.FromString,
                    response_serializer=cloud__pb2.GetPveInventoryResponse.SerializeToString,
            ),
            'GetCloudDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCloudDomain,
                    request_deserializer=cloud__pb2.GetCloudDomainRequest.FromString,
                    response_serializer=cloud__pb2.GetCloudDomainResponse.SerializeToString,
            ),
            'GetVmVarsBlake': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVmVarsBlake,
                    request_deserializer=cloud__pb2.GetVmVarsBlakeRequest.FromString,
                    response_serializer=cloud__pb2.GetVmVarsBlakeResponse.SerializeToString,
            ),
            'GetDnsARecordSet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDnsARecordSet,
                    request_deserializer=cloud__pb2.GetDnsARecordSetRequest.FromString,
                    response_serializer=cloud__pb2.GetDnsARecordSetResponse.SerializeToString,
            ),
            'CreateExternalAcmeTls': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateExternalAcmeTls,
                    request_deserializer=cloud__pb2.CreateExternalAcmeTlsRequest.FromString,
                    response_serializer=cloud__pb2.ExternalAcmeTlsResponse.SerializeToString,
            ),
            'DeleteExternalAcmeTls': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteExternalAcmeTls,
                    request_deserializer=cloud__pb2.DeleteExternalAcmeTlsRequest.FromString,
                    response_serializer=cloud__pb2.ExternalAcmeTlsResponse.SerializeToString,
            ),
            'CreateCNameRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCNameRecord,
                    request_deserializer=cloud__pb2.CreateCNameRecordRequest.FromString,
                    response_serializer=cloud__pb2.CNameRecordResponse.SerializeToString,
            ),
            'DeleteCNameRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCNameRecord,
                    request_deserializer=cloud__pb2.DeleteCNameRecordRequest.FromString,
                    response_serializer=cloud__pb2.CNameRecordResponse.SerializeToString,
            ),
            'GetK0sKubeconfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetK0sKubeconfig,
                    request_deserializer=cloud__pb2.GetK0sKubeconfigRequest.FromString,
                    response_serializer=cloud__pb2.GetKubeconfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.CloudService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protos.CloudService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CloudService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMasterKubeconfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/GetMasterKubeconfig',
            cloud__pb2.GetKubeconfigRequest.SerializeToString,
            cloud__pb2.GetKubeconfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterVars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/GetClusterVars',
            cloud__pb2.GetClusterVarsRequest.SerializeToString,
            cloud__pb2.GetClusterVarsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCloudFileSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/GetCloudFileSecret',
            cloud__pb2.GetCloudFileSecretRequest.SerializeToString,
            cloud__pb2.GetCloudFileSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCloudSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/CreateCloudSecret',
            cloud__pb2.CreateCloudSecretRequest.SerializeToString,
            cloud__pb2.CreateCloudSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCloudSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/DeleteCloudSecret',
            cloud__pb2.DeleteCloudSecretRequest.SerializeToString,
            cloud__pb2.DeleteCloudSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCloudSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/GetCloudSecret',
            cloud__pb2.GetCloudSecretRequest.SerializeToString,
            cloud__pb2.GetCloudSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCloudSecrets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/GetCloudSecrets',
            cloud__pb2.GetCloudSecretsRequest.SerializeToString,
            cloud__pb2.GetCloudSecretsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCephAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/GetCephAccess',
            cloud__pb2.GetCephAccessRequest.SerializeToString,
            cloud__pb2.GetCephAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSshKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/GetSshKey',
            cloud__pb2.GetSshKeyRequest.SerializeToString,
            cloud__pb2.GetSshKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProxmoxApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/GetProxmoxApi',
            cloud__pb2.GetProxmoxApiRequest.SerializeToString,
            cloud__pb2.GetProxmoxApiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProxmoxApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/CreateProxmoxApi',
            cloud__pb2.CreateProxmoxApiRequest.SerializeToString,
            cloud__pb2.CreateProxmoxApiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProxmoxApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/DeleteProxmoxApi',
            cloud__pb2.DeleteProxmoxApiRequest.SerializeToString,
            cloud__pb2.DeleteProxmoxApiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProxmoxHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/GetProxmoxHost',
            cloud__pb2.GetProxmoxHostRequest.SerializeToString,
            cloud__pb2.GetProxmoxHostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPveInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/GetPveInventory',
            cloud__pb2.GetPveInventoryRequest.SerializeToString,
            cloud__pb2.GetPveInventoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCloudDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/GetCloudDomain',
            cloud__pb2.GetCloudDomainRequest.SerializeToString,
            cloud__pb2.GetCloudDomainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVmVarsBlake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/GetVmVarsBlake',
            cloud__pb2.GetVmVarsBlakeRequest.SerializeToString,
            cloud__pb2.GetVmVarsBlakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDnsARecordSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/GetDnsARecordSet',
            cloud__pb2.GetDnsARecordSetRequest.SerializeToString,
            cloud__pb2.GetDnsARecordSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateExternalAcmeTls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/CreateExternalAcmeTls',
            cloud__pb2.CreateExternalAcmeTlsRequest.SerializeToString,
            cloud__pb2.ExternalAcmeTlsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteExternalAcmeTls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/DeleteExternalAcmeTls',
            cloud__pb2.DeleteExternalAcmeTlsRequest.SerializeToString,
            cloud__pb2.ExternalAcmeTlsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCNameRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/CreateCNameRecord',
            cloud__pb2.CreateCNameRecordRequest.SerializeToString,
            cloud__pb2.CNameRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCNameRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/DeleteCNameRecord',
            cloud__pb2.DeleteCNameRecordRequest.SerializeToString,
            cloud__pb2.CNameRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetK0sKubeconfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.CloudService/GetK0sKubeconfig',
            cloud__pb2.GetK0sKubeconfigRequest.SerializeToString,
            cloud__pb2.GetKubeconfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
